<?php
/**
 * @file
 * nysed_ct_resource_page.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function nysed_ct_resource_page_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['fieldblock-4bd1346e9553523a8985b9fba56ae55e'] = array(
    'cache' => 4,
    'css_class' => '',
    'custom' => '0',
    'delta' => '4bd1346e9553523a8985b9fba56ae55e',
    'module' => 'fieldblock',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'engageny' => array(
        'region' => 'sidebar_second',
        'status' => '1',
        'theme' => 'engageny',
        'weight' => '-58',
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => '0',
      ),
    ),
    'title' => '',
    'visibility' => '0',
  );

  $export['fieldblock-9273faedb1db131ce199378509629245'] = array(
    'cache' => 4,
    'css_class' => '',
    'custom' => '0',
    'delta' => '9273faedb1db131ce199378509629245',
    'module' => 'fieldblock',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'engageny' => array(
        'region' => 'sidebar_second',
        'status' => '1',
        'theme' => 'engageny',
        'weight' => '-53',
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => '0',
      ),
    ),
    'title' => '',
    'visibility' => '0',
  );

  $export['fieldblock-991d61e6fb181e3a4fae5875ed652145'] = array(
    'cache' => 4,
    'css_class' => '',
    'custom' => '0',
    'delta' => '991d61e6fb181e3a4fae5875ed652145',
    'module' => 'fieldblock',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'engageny' => array(
        'region' => 'sidebar_second',
        'status' => '1',
        'theme' => 'engageny',
        'weight' => '-52',
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => '0',
      ),
    ),
    'title' => '',
    'visibility' => '0',
  );

  $export['fieldblock-d69f2bfc4651e9fbdbc7d8983b2ad996'] = array(
    'cache' => 4,
    'css_class' => '',
    'custom' => '0',
    'delta' => 'd69f2bfc4651e9fbdbc7d8983b2ad996',
    'module' => 'fieldblock',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'engageny' => array(
        'region' => 'sidebar_second',
        'status' => '1',
        'theme' => 'engageny',
        'weight' => '-57',
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => '0',
      ),
    ),
    'title' => '',
    'visibility' => '0',
  );

  $export['views-BookSiblings-block_1'] = array(
    'cache' => -1,
    'css_class' => 'modulemenu',
    'custom' => '0',
    'delta' => 'BookSiblings-block_1',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'engageny' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'engageny',
        'weight' => '-38',
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => '0',
      ),
    ),
    'title' => '',
    'visibility' => '0',
  );

  $export['views-book_children-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => '0',
    'delta' => 'book_children-block',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'engageny' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'engageny',
        'weight' => '-48',
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => '0',
      ),
    ),
    'title' => '<none>',
    'visibility' => '0',
  );

  $export['views-book_children_ela_lessons-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => '0',
    'delta' => 'book_children_ela_lessons-block',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'engageny' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'engageny',
        'weight' => '-49',
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => '0',
      ),
    ),
    'title' => '',
    'visibility' => '0',
  );

  $export['views-book_lessons_siblings-block_1'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => '0',
    'delta' => 'book_lessons_siblings-block_1',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'engageny' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'engageny',
        'weight' => '-51',
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => '0',
      ),
    ),
    'title' => '',
    'visibility' => '0',
  );

  $export['views-ccls_math_block-block'] = array(
    'cache' => -1,
    'css_class' => 'ccls_standard',
    'custom' => '0',
    'delta' => 'ccls_math_block-block',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'engageny' => array(
        'region' => 'sidebar_first',
        'status' => '1',
        'theme' => 'engageny',
        'weight' => '-45',
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => '0',
      ),
    ),
    'title' => '',
    'visibility' => '0',
  );

  return $export;
}
